version: '3.8'

services:
  svelte-app:
    build: .
    ports:
      - "5000:5000"
    container_name: svelte-app
    volumes:
      - /app
      - /app/node_modules
    environment:
      NODE_ENV: development